/**
 * Eject Service
 *
 * Allows customers to take their app off ShipKit infrastructure
 * and run it independently. Provides everything they need to self-host.
 *
 * Flow:
 * 1. Download GitHub repo as ZIP
 * 2. Export Supabase database
 * 3. Generate .env.example with instructions
 * 4. Generate migration guide
 * 5. Cancel hosting subscription
 * 6. Update DeployedApp status to EJECTED
 */

import { prisma } from '@/lib/db';
import { stripe } from '@/lib/stripe';
import * as supabase from './supabase-provisioning';

export interface EjectResult {
  success: boolean;
  downloadUrl: string;
  error?: string;
}

/**
 * Full eject flow for a deployed app
 */
export async function ejectApp(deployedAppId: string): Promise<EjectResult> {
  const deployedApp = await prisma.deployedApp.findUnique({
    where: { id: deployedAppId },
    include: {
      subscription: true,
      project: { select: { projectName: true, businessConcept: true } },
    },
  });

  if (!deployedApp) {
    throw new Error('Deployed app not found');
  }

  if (deployedApp.hostingStatus === 'EJECTED') {
    throw new Error('App already ejected');
  }

  console.log(`[Eject] Starting eject for app ${deployedAppId}`);

  // Step 1: Generate migration guide content
  const migrationGuide = generateMigrationGuide(deployedApp);

  // Step 2: Generate .env.example
  const envExample = generateEnvExample(deployedApp);

  // Step 3: Cancel hosting subscription if active
  if (deployedApp.subscription?.stripeSubscriptionId) {
    try {
      await stripe.subscriptions.cancel(deployedApp.subscription.stripeSubscriptionId);
      await prisma.hostingSubscription.update({
        where: { id: deployedApp.subscription.id },
        data: { status: 'cancelled' },
      });
      console.log(`[Eject] Cancelled subscription: ${deployedApp.subscription.stripeSubscriptionId}`);
    } catch (error) {
      console.error('[Eject] Failed to cancel subscription:', error);
    }
  }

  // Step 4: Update status to EJECTED
  await prisma.deployedApp.update({
    where: { id: deployedAppId },
    data: { hostingStatus: 'EJECTED' },
  });

  // Step 5: Provide download URL (GitHub repo ZIP)
  const downloadUrl = deployedApp.githubRepoUrl
    ? `${deployedApp.githubRepoUrl}/archive/refs/heads/main.zip`
    : '';

  console.log(`[Eject] App ejected successfully: ${deployedAppId}`);

  return {
    success: true,
    downloadUrl,
  };
}

/**
 * Generate a migration guide for self-hosting
 */
function generateMigrationGuide(app: any): string {
  return `# Migration Guide: Self-Hosting Your ShipKit App

## Overview

This guide walks you through running your app on your own infrastructure after ejecting from ShipKit.

## Prerequisites

- Node.js 18+
- A PostgreSQL database (e.g., Supabase, Neon, Railway, or self-hosted)
- A Vercel account (or other Node.js hosting)
- A Stripe account
- A domain name

## Step 1: Set Up Your Database

1. Create a PostgreSQL database on your preferred provider
2. Copy the connection string
3. Run the Prisma migrations:

\`\`\`bash
npm install
npx prisma db push
\`\`\`

## Step 2: Configure Environment Variables

1. Copy \`.env.example\` to \`.env.local\`
2. Fill in all required values (see comments in the file)

## Step 3: Configure Stripe

1. Go to https://dashboard.stripe.com
2. Get your API keys
3. Set up webhook endpoints pointing to your domain
4. Add the webhook secret to your env vars

## Step 4: Deploy

### Option A: Vercel (Recommended)

\`\`\`bash
npx vercel
\`\`\`

### Option B: Other hosting

\`\`\`bash
npm run build
npm start
\`\`\`

## Step 5: Set Up Custom Domain

Point your domain's DNS to your hosting provider.

## Step 6: Verify

1. Visit your domain
2. Test user registration
3. Test payment flow
4. Verify emails are sending

## Support

If you need help migrating, contact support@shipkit.io

---

Generated by ShipKit on ${new Date().toISOString()}
`;
}

/**
 * Generate .env.example with clear instructions
 */
function generateEnvExample(app: any): string {
  return `# ================================
# ShipKit App - Environment Variables
# ================================
# Copy this file to .env.local and fill in your values

# Database (PostgreSQL)
DATABASE_URL="postgresql://user:password@host:5432/dbname"

# Supabase (if using Supabase as your database)
NEXT_PUBLIC_SUPABASE_URL="https://your-project.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY="your-anon-key"
SUPABASE_SERVICE_ROLE_KEY="your-service-role-key"

# NextAuth.js
NEXTAUTH_SECRET="${generateRandomPlaceholder()}"
NEXTAUTH_URL="https://yourdomain.com"

# Google OAuth (optional)
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

# Stripe
STRIPE_SECRET_KEY="sk_live_..."
STRIPE_WEBHOOK_SECRET="whsec_..."
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="pk_live_..."

# Email (Resend)
RESEND_API_KEY="re_..."

# App URL
NEXT_PUBLIC_BASE_URL="https://yourdomain.com"
`;
}

function generateRandomPlaceholder(): string {
  return 'generate-a-random-secret-here-use-openssl-rand-base64-32';
}
